### PR TITLE
Bumped Java SDK to 5.0.0

### PR DESCRIPTION
**Pull request by langsmith**
Part of https://github.com/mapbox/mapbox-java/issues/1100

### CODE REVIEW

**Comment by langsmith** [comment]
👉👉 @tobrun

**Comment by tobrun** [comment]
Rather not introduce androidX in a codebase that doesn't use jetifier and a Maps SDK that is still using support library. Let's hold off merging this until Maps 9.0.0 has been released.

**Comment by langsmith** [comment]
Ok, closing this. Ticketed https://github.com/mapbox/mapbox-plugins-android/issues/1089 as a reminder to eventually bump to at least `5.0.0`.

**Comment by langsmith** [comment]
Resolves #1089

**Comment by langsmith** [comment]
I'm going to do manual QA of test app before merging this

**Comment by langsmith** [comment]
Plugins are looking good with manual QA of this repo's test appl

**Pull request merged**
