### PR TITLE
Update style spec, gen new features, remove obsolete zIndex

### PR DESCRIPTION
**Pull request by tobrun**
This PR updates to the latest style spec and a recent pre release build of the Mapbox maps SDK.

Todo: 
 - [x] move towards using a git submodule of gl-js instead of copy/pasting this file into this repo
 - [x] remove old zIndex setup in favor of SymbolSortKey

### CODE REVIEW

**Comment by tobrun** [comment]
Note this PR also updates the Maps SDK to v7.4.0

**Comment by tobrun** [comment]
Been running some benchmarks for animating symbols (the animatied cars driving on a map example):

### no animation
Amount frames 296
Average FPS 55.82793574431573

### SymbolLayer - animated
Amount frames 374
Average FPS 41.81102010196368

### SymbolManager - before
Amount frames 209
Average FPS 25.355876562292273

### SymbolManager - without zIndex
Amount frames 233
Average FPS 28.16800860352976

Notes:
 - the low lever symbol layer is better for performance. If scale and performance are of importance use the low level symbol layer API instead
 - this improves performance a bit but was initially hoping on a larger impact.

**Comment by LukasPaczos** [comment]
I see nitpick errors, but regardless of that, try rebasing on `master` if you'll see unit tests failing (https://github.com/mapbox/mapbox-plugins-android/pull/923#issuecomment-494820566).

**Comment by tobrun** [comment]
> I see nitpick errors

that was because git submodules weren't correctly intialised on CI. This PR is ready for review.

**Pull request merged**
