### PR TITLE
Plugin LocationPicker

### PR DESCRIPTION
**Pull request by bkhezry**
#41 
image

pick the location from Mapbox map and return coordinates with an address of it from reverse geocode.
TODO: add search service that can find the location by name.

@zugaldia @tobrun

### CODE REVIEW

**Comment by zugaldia** [comment]
Look who's back :) Thank you @bkhezry for yet another contribution!

I'm tagging @cammace for PR review because he wrote our original location picker, and also @langsmith in case it's worth adopting this plugin in the demo app and update the current example.

**Comment by cammace** [comment]
thank you for this contribution @bkhezry this could be a great addition to the places plugin which recently got merged, let's us investigate the best way forward, we'll post back when we know more.

**Comment by cammace** [comment]
@bkhezry, thank you so much for this contribution. I extracted some of the ideas brought up from your PR and merged a Place Picker activity into master (in https://github.com/mapbox/mapbox-plugins-android/pull/262). It will be ready for use in your app with the next places plugin release. Let me know if you have any questions.

**Comment by bkhezry** [comment]
@cammace thank you :-), I'll see it.

**Pull request closed without merging**
