### PR TITLE
Bumped location layer plugin readme version to 0.5.1

### PR DESCRIPTION
**Pull request by langsmith**
Part of the 0.5.1 location layer plugin release: https://github.com/mapbox/mapbox-plugins-android/issues/499

### CODE REVIEW

**Comment by cammace** [comment]
@vladgheorghe if you are using the navigation SDK or another dependency that includes the location layer, you might see this issue. You can also logout your dependency tree to see what is bringing in the location layer. As for the release, https://repo1.maven.org/maven2/com/mapbox/mapboxsdk/mapbox-android-plugin-locationlayer/0.5.1/ confirms it is available through MavenCentral.

**Comment by cammace** [comment]
Looking over the repo and the files, it does appear that some of the files are missing, sorry for the misdirect @vladgheorghe. I'm currently looking into this, might need to do a 0.5.2 release to fix.

**Comment by cammace** [comment]
Hey all, the release of 0.5.2 happened yesterday which includes the missing files on Maven. Sorry for the issue

**Comment by diklimchuk** [comment]
@commace thank you, it works now!

**Pull request merged**
