### PR TITLE
Maps SDK v7.4.0

### PR DESCRIPTION
**Pull request by langsmith**
- [x] v7.4.0-alpha.1
- [x] v7.4.0-alpha.2
- [ ] v7.4.0-beta.1
- [x] v7.4.0

### CODE REVIEW

**Comment by langsmith** [comment]
They're not specific to `7.4.0` but I've filed https://github.com/mapbox/mapbox-plugins-android/issues/924 and https://github.com/mapbox/mapbox-plugins-android/issues/925, both of which I found as I was going through the app for `7.4.0-alpha.1` review.

**Comment by langsmith** [comment]
No issues with the example on `alpha.2`

**Comment by langsmith** [comment]
Very weird CI 💥 have been popping up for me on this branch. They don't appear on `master` and I already re-based. So strange. `nectar` is going out soon anyways 😕 .

**Comment by LukasPaczos** [comment]
The crashes were caused by the `mapbox-java` version mismatch between Maps SDK and plugins. Fixed in https://github.com/mapbox/mapbox-plugins-android/pull/923/commits/efd22049292b67bcae10d4f8bef97802b87a9fb7.

**Comment by langsmith** [comment]
Ah, ok. Thanks @LukasPaczos .

**Pull request merged**
