### PR TITLE
Downgrade log level of MapLocale no match scenarios

### PR DESCRIPTION
**Pull request by langsmith**
This pr is a duplicate of @snkashis' https://github.com/mapbox/mapbox-plugins-android/pull/992/. 

#992 was having an issue passing a test, I think because @snkashis isn't a part of the Mapbox team.

### CODE REVIEW

**Comment by tobrun** [comment]
> #992 was having an issue passing a test, I think because @snkashis isn't a part of the Mapbox team.

Ticketed this in https://github.com/mapbox/mapbox-plugins-android/issues/995

**Comment by snkashis** [comment]
@langsmith @tobrun When do you plan on releasing a new version incorporating these changes?

**Comment by langsmith** [comment]
Probably by the end of this week, @snkashis

**Comment by snkashis** [comment]
@langsmith cool, thank you

**Comment by snkashis** [comment]
@langsmith release still planned?

**Comment by langsmith** [comment]
@snkashis , I'm rolling with the release

https://github.com/mapbox/mapbox-plugins-android/issues/1038
https://github.com/mapbox/mapbox-plugins-android/pull/1039

I haven't actually released the new artifact files. Need some final eyes from a teammate. 

Unless there are any weird issues, `0.11.0` of the Localization Plugin should be available by the end of tomorrow.

**Comment by langsmith** [comment]
The `0.11.0` release of the Localization Plugin is complete

**Pull request merged**
