### PR TITLE
Harden against crashing when deleting an empty list

### PR DESCRIPTION
**Pull request by tobrun**
Refs https://github.com/mapbox/mapbox-plugins-android/issues/854#issuecomment-487719163, additionally annotates methods from AnnotationManager with null-ability.

cc @percula

### CODE REVIEW

**Comment by LukasPaczos** [comment]
Capturing from https://github.com/mapbox/mapbox-plugins-android/issues/854#issuecomment-487719163:
> It is caused by calling LineManager.delete(lines) with an empty list.

Is this for sure the cause of the crash? I wasn't able to reproduce with the introduced regression tests after commenting out the `AnnotationManager` changes.

I think it's good to skip the source update if the delete/create list is empty, but it doesn't seem to be related to the crash from the OP.

**Comment by percula** [comment]
I should note it only occurred when updating with an empty list while navigating to a new fragment. I double checked that it was callled from the main thread, but honestly am not sure why it only occurs in that circumstance.

**Comment by tobrun** [comment]
@LukasPaczos hmm yeah, removed the regression test, should be good to merge now. @percula you are calling updates when the underlying style (and thus sources/layers) have been destroyed.

**Comment by LukasPaczos** [comment]
@tobrun could you still include a test to ensure that we are not modifying the annotations array when adding/deleting and options are empty?

**Pull request closed without merging**
