### PR TITLE
Maps SDK bump to 6.4.0

### PR DESCRIPTION
**Pull request by langsmith**
Part of the Maps SDK 6.4.0 release

### CODE REVIEW

**Comment by langsmith** [comment]
@danesfeder @LukasPaczos @tobrun 

Something weird is going on with this bump and Firebase 🤔 . I've re-run the tests in CircleCI a couple of times, but it doesn't help. Have you seen this issue recently with prs in this repo?

**Comment by LukasPaczos** [comment]
The issue is that [the source is `null`](https://github.com/mapbox/mapbox-plugins-android/blob/master/app/src/androidTest/java/com/mapbox/mapboxsdk/plugins/utils/PluginGenerationUtil.kt#L40) and we are timing out. This behavior first appears with the `6.4.0-beta.1`.

**Comment by LukasPaczos** [comment]
Taking above back, it's actually[ the query](https://github.com/mapbox/mapbox-plugins-android/blob/master/app/src/androidTest/java/com/mapbox/mapboxsdk/plugins/utils/PluginGenerationUtil.kt#L41) that returns an empty list.

**Comment by langsmith** [comment]
Any next steps?

**Pull request merged**
